Engine
Twometer/NeonRacer pull request #3
Opened 2019-03-30 10:51 UTC by Twometer

2019-03-30 15:54 UTC, daniel-lerch requested changes
Den meisten Code verstehe ich nicht, aber das was ich inhaltlich verstehe, den Sinn davon aber nicht, habe ich kommentiert.

2019-03-30 15:54 UTC, daniel-lerch commented on src/src/main/java/neonracer/core/Timer.java
> +        this.partialTicks = this.passedTime;
Könntest du vielleicht Werte wie `passedTime` zuerst berechnen und dann den Feldern zuweisen? Selbst wenn diese Klasse nicht threadsicher sein muss, wäre das schöner.

2019-03-30 15:54 UTC, daniel-lerch commented on src/src/main/java/neonracer/core/Timer.java
> +    private static final long MAX_NS_PER_UPDATE = 10000000L;
Ich verstehe den Sinn von `MAX_NS_PER_UPDATE` nicht so wirklich. Die bisherige Implementierung soll verhindern, dass zu viele Ticks ausgeführt werden und dadurch die CPU überlastet wird. Dabei werden allerdings manche Ticks einfach verworfen. Soweit ich weiß soll ein solcher Timer aber eigentlich sicherstellen, dass die Physik immer korrekt ausgeführt wird und keine Eingaben verloren gehen, sondern einfach nur die Framerate reduziert wird.

2019-03-30 16:26 UTC, Twometer commented on src/src/main/java/neonracer/core/Timer.java
> +    private static final long MAX_NS_PER_UPDATE = 10000000L;
Joa den hab ich vor Jahren aus dem ersten Minecraft portiert und seither durch alle Games durchgeschlefit den Code, der funktioniert auch nicht mehr. Da steht noch ein Rewrite an.

2019-03-30 16:27 UTC, Twometer commented on src/src/main/java/neonracer/core/Timer.java
> +    private static final long MAX_NS_PER_UPDATE = 10000000L;
Die Implementation funktioniert aber anders, da werden keine Ticks verworfen und auch keine Framerate reduziert. Wenn er merkt die letzten 10 Ticks wurden nicht ausgeführt wegen einem Lag, führt er diese sofort aus und danach wieder mit 60 tps.

2019-04-05 16:33 UTC, daniel-lerch approved these changes

2019-04-09 10:13 UTC, merged