Setup instructions
Twometer/NeonRacer pull request #47
Opened 2020-09-22 11:01 UTC by daniel-lerch

Dieser Pull Request fügt Anleitungen für Spieler und Server-Administratoren hinzu, wie man NeonRacer herunterladen und ausführen kann.

Damit sollten die Verantwortlichen beim nächsten Tag der offenen Tür - sofern er überhaupt stattfinden darf - das Spiel präsentieren können (fixes #41).

2020-09-22 11:50 UTC, Twometer requested changes
Ist dir langweilig 😉? Hab hier lang keinen PR mehr gesehen. /OT

Der PR und die Doc schauen gut aus, allerdings stellt sich mir die Frage, ob das Teil mit JRE versionen > 1.8 läuft? Ich hab schon einige Anwendungen erlebt bei denen es mit Java 8 läuft, aber die gleiche Jar mit 11+ abstruse Fehlermeldungen wirft.

Nachdem das neue Doc außerdem für den TDOT gedacht ist, ist das Ding soweit überhaupt spielbar? Ich hatte beim letzten Versuch nicht unbedingt den Eindruck davon, vor allem nicht in dem Schulnetz.

2020-09-22 13:08 UTC, daniel-lerch commented
Ja, hier wurde in der Tat lange nicht mehr dran gearbeitet. Ich fände es aber schade, das Projekt nicht wenigstens so weit zu bringen, dass man damit Spaß haben kann, auch wenn es kein faires Rennen ist.

Ich weiß nicht, ob der Server mit JRE > 11 läuft. Die Anleitung, so wie sie da steht, habe ich auf einem 10 Jahren alten Laptop getestet. Mit `openjdk-11-jre` funktioniert der Server also auf jeden Fall. Für die UI fehlen Linux binaries diverser Libraries.

Ziel der Anleitung ist es, dass man das Spiel und einen Server zum Laufen bekommt. Dass das Spiel unfertig ist, ist glaube ich jedem klar. Die Performance würde ich gerne irgendwann mal wirklich in der Schule testen. Falls es wirklich unspielbar sein sollte, kann man ja #46 wieder aufmachen.

2020-09-23 08:23 UTC, Twometer approved these changes

2020-09-23 08:24 UTC, Twometer commented
Was würde denn eigentlich noch fehlen, damit es ein faires Rennen wird? nur mal so... ;D

2020-09-23 10:32 UTC, daniel-lerch commented
Eigentlich musst du dafür nur auf die offenen Issues schauen.
Es wäre mir eine große Hilfe, wenn du die Namen der jeweiligen Spieler über deren Autos rendern könntest (#40).
Die Autoplatzierung beim Rennstart (#42) wollte ich mir bei Zeiten mal anschauen.

2020-09-23 11:05 UTC, Twometer commented
Das mit den Namen der Spieler rendern ist so an sich gar kein Problem, und das kann ich auch gerne einbauen. Allerdings finde ich nicht raus, wie ich Entity und Player matchen kann xD der Player hat ne clientId und der Entity ne entityId. Vielleicht ist es zu lang her, aber ich weiß nicht wie das mapping ist. 

Funktioniert das mit dem clientId = entityId >> 32? wenn ja, haben wir da docs für?

2020-09-23 11:09 UTC, daniel-lerch commented
Ja, genau. Da musste man Bits shiften. Dokumentiert ist das in `Entity.proto` und implementiert in `NetworkClient.java:91`.

2020-09-23 11:09 UTC, merged